name: Publish
on:
  push:
    tags:
       - '*'
jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Run linters
        run: yarn run lint
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Notify
        uses: pcvg/slack-notification-action@main
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TITLE_SUCCESS: ""
          TITLE_FAIL: ""
          BODY_SUCCESS: "Vue-tags-input package update has been uploaded to npmjs successfully."
          BODY_FAIL: "Error processing vue-tags-input upload."
